### ISSUE TITLE
Empty pixels are not fully off.

### ISSUE THREAD

**Issue by tacsist** [night-crawler/led_matrix_monitoring#1]
Hi, really like your work. I have noticed the pixel stat should be off (i.e. the margin pixels between plots) are not completely off, but instead are slightly illuminated. Is this intended and if so is it possible to change in config?

**Comment by night-crawler** [comment]
Hi. Yep, it looks like a bug but with a led_matrix_daemon. Even if a pixel luminosity is reported as 0, it becomes 5. Because of that you and I are having this backlit. Thanks for noticing it, I'll try to fix it soon.

**Comment by night-crawler** [comment]
Hi again. I forgot I was messing around with grayscale conversion: https://github.com/night-crawler/led_matrix_daemon/commit/59fcdfec37f296d67c336d79ab345a91a51f7edd#diff-d71f5e1c5152f37d841c9a4fef9e6f242cb960401b86e181108174ee59c3ae3aL57-L61

Also, here was a bug in `led_matrix_monitoring` in the default config causing graphs 1-pixel overlap.

Both packages were updated. Please, feel free to close the issue if everything's OK on your side. Thank you.

**Comment by tacsist** [comment]
Yep, all good on my end now. You absolute beast, ty <3
