### ISSUE TITLE
A reboot is needed to reconnect the LED Matrix to the daemon

### ISSUE THREAD

**Issue by Franscobec** [night-crawler/led_matrix_monitoring#4]
As I briefly mentioned in #2, if the LED Matrix gets disconnected from the laptop, the systemd service fails to communicate with the LED Matrix and also fails to restart.
It's mostly a user experience issue, as it's slightly annoying to have to reboot every single time I have to remove a part of the input deck (and therefore disconnect the LED Matrix)

**Comment by night-crawler** [comment]
The device indices are being reassigned after you pull them out. Initially, they're set to `/dev/ttyACM{0,1}` but after the reboot they change to something like `/dev/tty/ACM{2,3}`.

I'm considering using some udev rules to solve this but I'm not sure which ones at the moment.

I thought I could differentiate the devices by serial numbers, but they appear to be the same:

```bash
❯ udevadm info --name=/dev/ttyACM2 --attribute-walk | grep -i serial
    ATTRS{serial}=="FRAKDEBZ0100000000"
    ATTRS{serial}=="0000:c1:00.3"
❯ udevadm info --name=/dev/ttyACM3 --attribute-walk | grep -i serial
    ATTRS{serial}=="FRAKDEBZ0100000000"
    ATTRS{serial}=="0000:c1:00.3"
```

A dumb mitigation would be accepting a list of possible devices, but I'm not that desperate yet.

**Comment by night-crawler** [comment]
Next thing, is that while the port is being held, the kernel allocates new numbers. I'll try releasing the port when I get broken pipe and after that it might work again. Need some more time for testing.

**Comment by night-crawler** [comment]
Updated aur. Works for me now.

**Comment by Franscobec** [comment]
> Updated aur. Works for me now.

Thank you, will try this out now.

**Comment by Franscobec** [comment]
I am unable to update the daemon from the AUR.
![image](https://github.com/user-attachments/assets/ff42eddc-a006-4fca-9831-24a610e570ec)

Right now the LED matrix do not come back after being reconnected, probably due to this issue

**Comment by night-crawler** [comment]
> Right now the LED matrix do not come back after being reconnected, probably due to this issue

This is weird. I recompiled it just now and everything's fine one my side. 

I am using rust nightly to build the package:

```
build() {
  cd "$pkgname-$pkgver"
  export RUSTUP_TOOLCHAIN=nightly
  export RUSTFLAGS="--cfg tokio_unstable --cfg=tokio_unstable"
  export CC=clang
  cargo build --release --locked
}
```

Are you sure you are not defining something like `RUSTUP_TOOLCHAIN` on your side?

**Comment by Franscobec** [comment]
> I am using rust nightly to build the package:

I was using the standard rust package. Installing nightly fixed the issue.
